name: Build and Deploy via SFTP

on:
  push:
    branches:
      - main  # or your default branch name
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '22'  # or your preferred Node.js version
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --production

      - name: Build project
        run: yarn build
        env:
          NODE_ENV: production

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: './dist/*'
          remote_path: ${{ secrets.SFTP_PATH }}
          sftp_only: true
          password: ${{ secrets.SFTP_PASSWORD }}

      - name: Deployment Status
        if: always()
        run: |
          if [ ${{ job.status }} = "success" ]; then
            echo "✅ Deployment successful"
          else
            echo "❌ Deployment failed"
          fi
